## Introducing ```numpy``` and arrays

To begin processing image data, we need to understand what's going on behind the scenes.

We can do that using a library called ```numpy```, which stands for __Numerical Python__. 

In general, you should use this library when you want to do fancy mathemtical operations with numbers, especially if you have arrays or matrices.

In [2]:
# tools for interacting with the operating system
import os
from pathlib import Path

# scientific python tool for 
import numpy as np # creating an abbreviation to save keystrokes

In [8]:
SAMPLE_DIR = Path("../../../CDS-VIS/test_samples")
assert SAMPLE_DIR.exists()
file_path = SAMPLE_DIR / "sample-data-01.csv"

In [16]:
data = np.loadtxt(file_path, delimiter=",")

(60, 40)

The expression ```numpy.loadtxt(...)``` is a function call that asks Python to run the function ```loadtxt``` which belongs to the ```numpy``` library. This dotted notation is used everywhere in Python: the thing that appears before the dot contains the thing that appears after.


```numpy.loadtxt``` has two parameters: the name of the file we want to read and the delimiter that separates values on a line. These both need to be character strings (or strings for short), so we put them in quotes.

__Assign to variable__

In [20]:
data = np.loadtxt(file_path, delimiter=",")

In [21]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [22]:
print(type(data))

<class 'numpy.ndarray'>


__numpy.ndarray__ tells us that we are working with an N-dimensional array

In this case, it's 2-dimensional

__Index__

Indexing is similar to lists and strings, but we need to inlcude both row and column

__Question:__ What is the middle value of the array?

In [18]:
x[int(x.shape[0]/2), int(x.shape[1]/2)]


13.0

<img src="../../CDS-VIS/test_samples/python-zero-index.svg">

__Slice__

An index like [30, 20] selects a single element of an array, but we can select whole sections as well. 

For example, we can select the first ten columns of values for the first four rows like this:

First ten columns, rows five-ten

__Select only one row__

__Select only one column__

__Numpy functions__

How to access help...

__Operation across rows__

"Average score per day"

__Operation along columns__

"Average score per patient"

<img src="../../CDS-VIS/test_samples/numpy-axes.png">

This is a good overview to show how things work wiht ```numpy```:

https://www.sharpsightlabs.com/blog/numpy-axes-explained/

## Basic image processing with OpenCV

We start by loading all of the modules we'll need for this class

In [ ]:
# We need to incldue the home directory in our path, so we can read in our own module.
import sys
sys.path.append(os.path.join("..", "..", "CDS-VIS"))

In [ ]:
# python framework for working with images
import cv2

# some utility functions for plotting images
from utils.imutils import jimshow

__Read image__

We can load an image using a handy function from OpenCV

__Save image__

__Inspect image__

## What is an image?

__Remember how ```numpy``` arrays work!__

ROWSxCOLUMNS == HEIGHTxWIDTH

In our image, there are 228*350 = 79,800 pixels

__What about the last one?__

<img src="../../CDS-VIS/test_samples/3-channels.png">

__NB!__

```OpenCV``` stores RGB tuples in REVERSE ORDER

__What colour is a specific pixel?__

__Modify colour__

__Image slice__

__Change corner colour__